// VsCode Extension: REST Client
// https://marketplace.visualstudio.com/items?itemName=humao.rest-client

// Get all records
GET http://localhost:3000/followers

###

// Get record by ID
GET http://localhost:3000/followers/65a6dc60685c6e08842a2db4

###

// Create new record
POST http://localhost:3000/followers
Content-Type: application/json

{
    "name": "Potato",
    "followed": true
}

###

// Delete record by ID
DELETE http://localhost:3000/followers/65a6d5dd834e474c2345ef66

### 

// Update record by ID
PATCH http://localhost:3000/followers/65a6ea46173637e91fb0af66
Content-Type: application/json

{
    "name": "Kyo Kusanagi"
}